// Credit to LUNI for most of this.

#pragma once

#include <iostream>
#include "MessageIdentifiers.h"
#include <BitStream.h>
#include <iostream>
#include <string.h>
#include <intrin.h>
#include <string>

using namespace RakNet;
using namespace std;

// RemoteConnection IDs
enum RemoteConnection : unsigned char
{
	GENERAL = 0,
	AUTH,
	CHAT,
	UNKNOWNCONN,
	WORLD,
	SERVER
};

// IDs for all servers
enum ServerPacketID : unsigned char
{
	VERSION_CONFIRM = 0,
	DISCONNECT_NOTIFY,
	GENERAL_NOTIFY,
};

// IDs for Auth Server
enum AuthPacketID : unsigned char
{
	LOGIN_REQUEST = 0,
	LOGOUT_REQUEST,
	CREATE_NEW_ACCOUNT_REQUEST,
	LEGOINTERFACE_AUTH_RESPONSE,
	SESSIONKEY_RECIEVED_CONFIRM,
	RUNTIME_CONFIG
};

// IDs for Chat Server
enum ChatPacketID : unsigned char
{
	// IDs for Chat
	LOGIN_SESSION_NOTIFY = 0,
	GENERAL_CHAT_MESSAGE,
	PRIVATE_CHAT_MESSAGE,
	USER_CHANNEL_CHAT_MESSAGE,
	WORLD_DISCONNECT_REQUEST,
	WORLD_PROXIMITY_RESPONSE,
	WORLD_PARCEL_REQUEST,
	ADD_FRIEND_REQUEST,
	ADD_FRIEND_RESPONSE,
	REMOVE_FRIEND,
	GET_FRIENDS_LIST,
	ADD_IGNORE,
	REMOVE_IGNORE,
	GET_IGNORE_LIST,
	TEAM_MISSED_INVITE_CHECK,
	TEAM_INVITE,
	TEAM_INVITE_RESPONSE,
	TEAM_KICK,
	TEAM_LEAVE,
	TEAM_SET_LOOT,
	TEAM_SET_LEADER,
	TEAM_GET_STATUS
};

// IDs for World Server
enum WorldPacketID : unsigned char
{
	CLIENT_VALIDATION = 1,
	CLIENT_CHARACTER_LIST_REQUEST,
	CLIENT_CHARACTER_CREATE_REQUEST,
	CLIENT_LOGIN_REQUEST,
	CLIENT_GAME_MSG,
	CLIENT_CHARACTER_DELETE_REQUEST,
	CLIENT_CHARACTER_RENAME_REQUEST,
	CLIENT_HAPPY_FLOWER_MODE_NOTIFY,
	CLIENT_SLASH_RELOAD_MAP,
	CLIENT_SLASH_PUSH_MAP_REQUEST,
	CLIENT_SLASH_PUSH_MAP,
	CLIENT_SLASH_PULL_MAP,
	CLIENT_LOCK_MAP_REQUEST,
	CLIENT_GENERAL_CHAT_MESSAGE,
	CLIENT_HTTP_MONITOR_INFO_REQUEST,
	CLIENT_SLASH_DEBUG_SCRIPTS,
	CLIENT_MODELS_CLEAR,
	CLIENT_EXIBIT_INSERT_MODEL,
	CLIENT_LEVEL_LOAD_COMPLETE,
	CLIENT_TMP_GUILD_CREATE,
	CLIENT_ROUTE_PACKET,
	CLIENT_POSITION_UPDATE,
	CLIENT_MAIL,
	CLIENT_WORD_CHECK,
	CLIENT_STRING_CHECK
};

void WriteStringToBitStream(const char* myString, int stringSize, int maxChars, RakNet::BitStream* output);

void CreatePacketHeader(MessageID messageId, unsigned short connectionType, unsigned long internalPacketId, BitStream* output);
