#pragma once

// Credit goes to LUNI for this one, too

enum UserSuccess : char {
	SUCCESS = 0x01,
	BANNED,
	PERMISSION_LOW,
	UNKNOWN1,
	UNKNOWN2,
	INVALID_PASS,
	LOCKED,
	INVALID_USER,
	ACTIVATION_PENDING,
	ACCOUNT_DISABLED,
	GAME_TIME_EXPIRED,
	FREE_TRIAL_ENDED,
	PLAY_SCHEDULE_NOT_ALLOWED,
	ACCOUNT_NOT_ACTIVATED
};